default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fullstack_task_development
  username: <%= ENV.fetch("DB_USERNAME") {} %>
  password: <%= ENV.fetch("DB_PASSWORD") {} %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>

test:
  <<: *default
  database: fullstack_task_test
  username: <%= ENV.fetch("DB_USERNAME") {} %>
  password: <%= ENV.fetch("DB_PASSWORD") {} %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>

staging:
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>

production:
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
